model_organism:
  name: qwen_local
  description: Local Qwen2.5-3B for highest_bid_military
  config: {}

environments:
  - name: highest_bid_military
    description: Highest-bid military environment
    eval_config:
      head: 5

